#!/usr/bin/env python3

"""
Builds webinclude/examples.py using the example files in
webinclude/examples/*.cc.

The first line of the files in that directory should start with "# Title: ".
This title will appear in the web interface. The files are sorted by file name
in the interface.
"""

import glob

filenames = sorted(glob.glob("webinclude/examples/*.cc"))
assert filenames

TITLEMARKER = "# Title: "

def gettitlecontents(content):
	firstline, sep, restlines = content.partition("\n")
	assert firstline.startswith(TITLEMARKER)
	return (firstline[len(TITLEMARKER):], restlines.strip())

predefined_files = [gettitlecontents(open(filename).read())
					for filename in filenames]

print("# This file (webinclude/examples.py) is automatically generated by build-examples.py.")
print()

print("predefined_files = " + repr(predefined_files))
print()
print("# End of autogenerated file.")